ChainID = '2358'
ChainType = 'optimismBedrock' # Kroma is based on the Optimism Bedrock architechture
FinalityDepth = 500
LogPollInterval = '2s'
LinkContractAddress = '0x04290A3bEAC157bA1E9B126708D26535CF90D946'
NoNewHeadsThreshold = '40s'
MinIncomingConfirmations = 1

[GasEstimator]
EIP1559DynamicFees = true
PriceMin = '1 wei'
BumpMin = '100 wei'

[GasEstimator.BlockHistory]
BlockHistorySize = 60

[Transactions]
ResendAfterThreshold = '30s'

[HeadTracker]
HistoryDepth = 500

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1

[OCR2.Automation]
GasLimit = 6500000