ChainID = '59144'
# Block time 12s, finality < 60m
FinalityDepth = 300
# Blocks are only emitted when a transaction happens / no empty blocks
NoNewHeadsThreshold = '0'

[GasEstimator]
BumpPercent = 40

[Transactions]
# increase resend time to align with finality
ResendAfterThreshold = '3m'

# set greater than finality depth
[HeadTracker]
HistoryDepth = 350

# Linea uses 200 blocks to estimate gas price
[GasEstimator.BlockHistory]
BlockHistorySize = 200
